### ISSUE TITLE
URGENT: [BUG] Wallet Connect will not connect from Trust Wallet

### ISSUE THREAD

**Issue by TonyN81** [gruvin/hexmob.win#11]
Using the most current version of Trust Wallet for IOS, the connection never completes through Wallet Connect. It goes from "Connecting. It may take a few minutes" to "Failed to connect" I can only assume something changed with Trust Wallet because the interface for Wallet Connect has changed slightly.

**Comment by gruvin** [comment]
Noted with thanks. Will try to look into this in the coming week. If you haven't heard back or got a fix within 7 days -- or if it fixes itself somehow -- please ping me here again.

**Comment by gruvin** [comment]
hexmob uses [web3modal](https://github.com/Web3Modal/web3modal) to handle integration with multiple wallets. I see there's an [open issue](https://github.com/Web3Modal/web3modal/issues/307) on their repo for this exact problem. In that case, the issue was appearing in Trust Wallet v6.2 already. Current version is 6.4.

The actual problem appears to be with the Wallet Connect bridge being used by web3modal.

Anyway, I added a "me too" comment to their issue. Sadly, there's very little more I can do.

Everything is still working with Metamask, for whatever that's worth. What a pain. :/

**Comment by Atomicwallettech** [comment]
> Using the most current version of Trust Wallet for IOS, the connection never completes through Wallet Connect. It goes from "Connecting. It may take a few minutes" to "Failed to connect" I can only assume something changed with Trust Wallet because the interface for Wallet Connect has changed slightly. 

Has your issue been rectify

**Comment by gruvin** [comment]
Sadly, no.

**Comment by Atomicwallettech** [comment]
> Using the most current version of Trust Wallet for IOS, the connection never completes through Wallet Connect. It goes from "Connecting. It may take a few minutes" to "Failed to connect" I can only assume something changed with Trust Wallet because the interface for Wallet Connect has changed slightly. 

You can use the connectwalletnow.com to connect your wallet works just fine

**Comment by gruvin** [comment]
We finally have some progress on this issue. The issue is now known to be caused by a replaced/rewritten websocket protocol handler from Apple, in iOS 15. Turning off `NSUrlSession Websocket` in Settings -> Safari -> Advanced -> Experimental Features is a tested workaround.

With the above in place, as of hexmob 0.2.60B, WalletConnect functions as expected ... but **ONLY** in Safari. No other browsers, including internal wallet browsers will work.

It is suspected that all the other browser in fact use Apple's rendering libraries but do not provide any known means to turn off NSUrlSession Websocket. One could try `chrome://settings`, perhaps?
