### ISSUE TITLE
Wallet connect with metamask on mobile

### ISSUE THREAD

**Issue by peanut54066** [gruvin/hexmob.win#13]
I have not been able to connect MetaMask to tshare app in several days.

**Comment by gruvin** [comment]
We finally have some progress on this issue. The issue is now known to be caused by a replaced/rewritten websocket protocol handler from Apple, in iOS 15. Turning *off* `NSUrlSession Websocket` in Settings -> Safari -> Advanced -> Experimental Features is a tested workaround.

With the above in place, as of hexmob 0.2.60B, WalletConnect functions as expected ... but *ONLY* in Safari. No other browsers, including internal wallet browser will work.

It is suspected that all the other browser in fact use Apple's rendering libraries but do not provide any known means to turn off `NSUrlSession Websocket`.  One could try chrome://settings, perhaps?

**Comment by gruvin** [comment]
Please refer to issue #11 for further information when it comes to hand.
