### ISSUE TITLE
Future market supply

### ISSUE THREAD

**Issue by discochuck** [gruvin/hexmob.win#14]
Guessing it's an upstream issue but figured I'd send the bug your way.

Looks like the future market supply isn't loading.

**Comment by gruvin** [comment]
Thanks for the report. I have been aware for a while now but it's good to have the issue logged here.

The issue is semi upstream. My data aggregator is apparently requesting too much data, too often -- despite its very existence being to prevent exactly that. Due to request data throttling by the upstream party and data being added faster than such allows, the system has entered a negative feedback loop -- and may not ever be able to catch up. :-(

There may be a way to fix it by paying for more data. I'm not sure there will be a reasonable solution. We may have to drop the feature. :'( Frankly, I find this one a bit overwhelming and I'm simply not sure what to do.

For what it's worth, this project was never originally intended to be used by others as it was a mere learning exercise for myself personally. I was glad to share it but continued development is, shall we just say, under resourced. Mati has been looking for additional/replacement developers to help out but no joy to date.

That said -- I do pledge to try and fix this and add the other feature requests, eventually. Biting off more than I can chew seems to be a pattern in my life. 📦
