### ISSUE TITLE
[BUG]: If a stake has completed, change the EES button

### ISSUE THREAD

**Issue by discochuck** [gruvin/hexmob.win#15]
If stake complete, change the early end stake button to be "end stake button" perhaps change the colour to a less "caution! Don't nuke 100% of your principal" Red, to a " good job, you're not fucking your self" Green?

Dealers choice. 

Take care, 
-c

**Comment by gruvin** [comment]
That's how it is supposed to be working already and always had before, as
far as I know. I put a lit of effort into all of that and it was fine,
WEIRD. There haven't been any changes made by me for a long time now. Did
this strangeness just start happening recently?

I also note that more stuff broken on macOS after a recent update. Probably
similar to under iOS, by the looks. For me, this means my app *doesn't work
on ANYTHING Apple any more *and *there's apparently nothing I can do about
it.* Pissed. I guess it still works under Windows. I should probably check.

I probably shouldn't state the following in such a public place but
whatever ...

Sadly, right now, I do not possess the mental wherewithal to approach any
of this. Matty is (unconsciously?) ignoring my pleas for help (I guess he's
just busy or otherwise simply unable and presumably unaware or something?)
... though he still asks me to join QuantGang etc. That's not likely to
happen any time soon -- if ever again.  I'm alone, isolated and as such
honestly just don't care any more. I tried to do the community thing but it
just isn't me. It's set my mental health back a long way, despite initially
helping.

Thank you for your support to date @discoduck. You're the ONLY person who
ever reached out, not just wanting something, never to be heard from again.
Matty seems busy with who knows what and hasn't been replying to my stuff
for some weeks now. I have no idea what's going on in his neck of the woods
and thus no idea what's going on in the "real" community AT ALL, besides
bickering and BS on Twitter, which I no longer read.

I'm out.

Sorry.

**Comment by gruvin** [comment]
Is that not more or less exactly what happens already? It used to be?  :/ I'll take a look. Thanks.

**Comment by gruvin** [comment]
You were right (go figure :P). How did I miss that? :/ Fixed in 0.2.60B. Thanks again.
