### ISSUE TITLE
Read only view

### ISSUE THREAD

**Issue by discochuck** [gruvin/hexmob.win#5]
Akin to apphex.win, it'd be cool to be able to specify an eth address and show a read only version within the interface.

**Comment by gruvin** [comment]
Thanks for the request.

There's actually already a feature for that, though not advertized. It does require that one wallet be connected, just to get the data feed connected. Works like this ...

```https://hexmob.win/?account=0x.......0:optional_Name```

(note the colon : between address and the optional name.)

You can add more accounts in the same fashion but using `&` in front, instead of `?`. Eg...

```https://hexmob.win/?account=0x.......0:optional_label&account=0x.......0:Dream+Account```

(the ```+``` gets converted to a space, as is convention with URLs.)

Does that suffice?

I do have a TODO item for creating a user interface to more conveniently add/remove such addresses but it's way down the list at this stage.

**Comment by discochuck** [comment]
That's awesome! Thank you!
